DROP TABLE EQUIPOS;
CREATE TABLE EQUIPOS(
RAZON_SOC VARCHAR(30) PRIMARY KEY,
ESTADIO VARCHAR(30),
ESCUDO VARCHAR(10), --rutaImagen--
AÑO_FUNDAC INT
);

DROP TABLE JUGADORES;
CREATE TABLE JUGADORES(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOM_JUG VARCHAR(30),
EDAD INT,
NACIONALIDAD VARCHAR(10),
EQUIPO VARCHAR(30),
POSICION VARCHAR(10),
FOREIGN KEY(EQUIPO) REFERENCES EQUIPOS(RAZON_SOC) ON DELETE CASCADE 
);

INSERT INTO EQUIPOS VALUES('REAL BETIS BALOMPIE', 'BENITO VILLAMARIN', 'betis.png', 1907);
INSERT INTO EQUIPOS VALUES('REAL MADRID CF', 'SANTIAGO BERNABEU', 'madrid.png', 1902);
INSERT INTO EQUIPOS VALUES('FC BARCELONA', 'CAMP NOU', 'barce.png', 1899);
INSERT INTO EQUIPOS VALUES('SEVILLA FC', 'SANCHEZ PIZJUAN', 'sevi.png', 1890);
INSERT INTO EQUIPOS VALUES('ATCO MADRID', 'CALDERON', 'atco.png', 1903);

INSERT INTO JUGADORES VALUES(1, 'BENZEMA', 32, 'FRANCIA', 'REAL MADRID CF', 'DELANTERO');
INSERT INTO JUGADORES VALUES(2, 'BORJA IGLESIAS', 27, 'ESPAÑA', 'REAL BETIS BALOMPIE', 'DELANTERO');
INSERT INTO JUGADORES VALUES(3, 'MESSI', 32, 'ARGENTINA', 'FC BARCELONA', 'DELANTERO');
INSERT INTO JUGADORES VALUES(4, 'BANEGA', 31, 'ARGENTINA', 'SEVILLA FC', 'MEDIO');
INSERT INTO JUGADORES VALUES(5, 'MORATA', 27, 'ESPAÑA', 'ATCO MADRID', 'DELANTERO');
INSERT INTO JUGADORES VALUES(6, 'SAUL', 25, 'ESPAÑA', 'ATCO MADRID', 'MEDIO');
INSERT INTO JUGADORES VALUES(7, 'SIDNEI', 30, 'PORTUGAL', 'REAL BETIS BALOMPIE', 'DEFENSA');
INSERT INTO JUGADORES VALUES(8, 'VARANE', 26, 'FRANCIA', 'REAL MADRID CF', 'DEFENSA');
INSERT INTO JUGADORES VALUES(9, 'RAKITIC', 31, 'CROACIA', 'FC BARCELONA', 'MEDIO');
INSERT INTO JUGADORES VALUES(10, 'TER STEGEN', 27, 'ALEMANIA', 'FC BARCELONA', 'PORTERO');
INSERT INTO JUGADORES VALUES(11, 'DE JONG', 29, 'HOLANDA', 'SEVILLA FC', 'DELANTERO');
INSERT INTO JUGADORES VALUES(12, 'OBLAK', 27, 'ESLOVENIA', 'ATCO MADRID', 'PORTERO');
INSERT INTO JUGADORES VALUES(13, 'JOAQUIN', 38, 'ESPAÑA', 'REAL BETIS BALOMPIE', 'MEDIO');
INSERT INTO JUGADORES VALUES(14, 'MODRIC', 34, 'CROACIA', 'REAL MADRID CF', 'MEDIO');
INSERT INTO JUGADORES VALUES(15, 'JOEL', 29, 'ESPAÑA', 'REAL BETIS BALOMPIE', 'PORTERO');
